global:
  resolve_timeout: 5m
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@defi-arbitrage.com'

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    - receiver: 'critical-alerts'
      match:
        severity: critical
      continue: true

    - receiver: 'warning-alerts'
      match:
        severity: warning
      continue: true

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'alerts@defi-arbitrage.com'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'critical-alerts@defi-arbitrage.com'
        send_resolved: true
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#critical-alerts'
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: 'warning-alerts@defi-arbitrage.com'
        send_resolved: true
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#warning-alerts'
        send_resolved: true

  # Optional: Telegram notification
  - name: 'telegram-alerts'
    webhook_configs:
      - url: 'http://telegram-bot:8080/alerts'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'job']

templates:
  - '/etc/alertmanager/templates/*.tmpl'