global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'arbitrage_bot'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    
  - job_name: 'blockchain_nodes'
    static_configs:
      - targets: ['ethereum-node:9090', 'bsc-node:9090']
    
  - job_name: 'exchange_api_metrics'
    scrape_interval: 30s
    static_configs:
      - targets: ['cex-metrics:9100', 'dex-metrics:9100']

  - job_name: 'gas_price_metrics'
    scrape_interval: 1m
    static_configs:
      - targets: ['gas-price-exporter:9200']

# Custom Scrape Configurations for Arbitrage Bot
  - job_name: 'arbitrage_opportunities'
    metrics_path: '/arbitrage/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:8000']

# Kubernetes Service Discovery (Optional)
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)